### ISSUE TITLE
Ubuntu 1404 LTS dependency issue

### ISSUE THREAD

**Issue by Shironofenny** [Shironofenny/BioEECoins#1]
Unable to run this program under Ubuntu 1404.3 LTS, the following error is generated by the python interpreter:

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import ok
  File "/home/yihan/Work/BioEECoins/ok.py", line 26, in <module>
    _ok = swig_import_helper()
  File "/home/yihan/Work/BioEECoins/ok.py", line 22, in swig_import_helper
    _mod = imp.load_module('_ok', fp, pathname, description)
ImportError: libudev.so.0: cannot open shared object file: No such file or directory

**Comment by Shironofenny** [comment]
This is in fact due to the fact that libudev0 is removed from Ubuntu 1404 official repository. Download the [deb file](http://packages.ubuntu.com/precise/libudev0) and install using dpkg, you will find the issue fixed.
